apiVersion: v1
kind: Service
metadata:
  name: test-pipeline
  namespace: pipeline
spec:
  ports:
  - nodePort: 30754
    port: 4200
    targetPort: 4200
  selector:
    app: test-pipeline
  type: NodePort
